=== jack-whatley/katabasis/.old/manager/targets.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "dev.jackwhatley.katabasis.targets.schema.json",
    "title": "Targets Schema",
    "description": "A schema for Katabasis Targets",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "The target's name"
            },
            "slug": {
                "type": "string",
                "description": "The targets slug parameter on Thunderstore"
            },
            "loader": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the plugin loader"
                    },
                    "packageOverride": {
                        "type": "string",
                        "description": "Override of the default mod package download"
                    },
                    "required": ["name"]
                }
            },
            "platforms": {
                "type": "object",
                "properties": {
                    "steam": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "number",
                                "description": "The steam id of the target"
                            }
                        }
                    }
                }
            },
            "required": ["name", "slug", "loader", "platforms"]
        }
    }
}

=== jack-whatley/katabasis/.old/manager/targets.json
[
    {
        "name": "Lethal Company",
        "slug": "lethal-company",
        "loader": {
            "name": "BepInEx"
        },
        "platforms": {
            "steam": {
                "id": 1966720
            }
        }
    },
    {
        "name": "R.E.P.O.",
        "slug": "repo",
        "loader": {
            "name": "BepInEx"
        },
        "platforms": {
            "steam": {
                "id": 3241660
            }
        }
    },
    {
        "name": "Valheim",
        "slug": "valheim",
        "loader": {
            "name": "BepInEx",
            "packageOverride": "denikson-BepInExPack_Valheim"
        },
        "platforms": {
            "steam": {
                "id": 892970
            }
        }
    }
]
